// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: barber_schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteBarberSchedule = `-- name: DeleteBarberSchedule :exec
DELETE FROM barber_schedules WHERE barber_id = $1 AND dow = $2
`

type DeleteBarberScheduleParams struct {
	BarberID uuid.UUID `json:"barber_id"`
	Dow      int32     `json:"dow"`
}

func (q *Queries) DeleteBarberSchedule(ctx context.Context, arg DeleteBarberScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteBarberSchedule, arg.BarberID, arg.Dow)
	return err
}

const getScheduleForBarberDOW = `-- name: GetScheduleForBarberDOW :one
SELECT id, barber_id, dow, open_time, close_time FROM barber_schedules
WHERE barber_id = $1 AND dow = $2
LIMIT 1
`

type GetScheduleForBarberDOWParams struct {
	BarberID uuid.UUID `json:"barber_id"`
	Dow      int32     `json:"dow"`
}

func (q *Queries) GetScheduleForBarberDOW(ctx context.Context, arg GetScheduleForBarberDOWParams) (BarberSchedule, error) {
	row := q.db.QueryRow(ctx, getScheduleForBarberDOW, arg.BarberID, arg.Dow)
	var i BarberSchedule
	err := row.Scan(
		&i.ID,
		&i.BarberID,
		&i.Dow,
		&i.OpenTime,
		&i.CloseTime,
	)
	return i, err
}

const listSchedulesForBarber = `-- name: ListSchedulesForBarber :many
SELECT id, barber_id, dow, open_time, close_time FROM barber_schedules
WHERE barber_id = $1
ORDER BY dow ASC
`

func (q *Queries) ListSchedulesForBarber(ctx context.Context, barberID uuid.UUID) ([]BarberSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesForBarber, barberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BarberSchedule{}
	for rows.Next() {
		var i BarberSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BarberID,
			&i.Dow,
			&i.OpenTime,
			&i.CloseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBarberSchedule = `-- name: UpsertBarberSchedule :one
INSERT INTO barber_schedules (barber_id, dow, open_time, close_time)
VALUES ($1, $2, $3, $4)
ON CONFLICT (barber_id, dow) DO UPDATE
  SET open_time = EXCLUDED.open_time,
      close_time = EXCLUDED.close_time
RETURNING id, barber_id, dow, open_time, close_time
`

type UpsertBarberScheduleParams struct {
	BarberID  uuid.UUID `json:"barber_id"`
	Dow       int32     `json:"dow"`
	OpenTime  string    `json:"open_time"`
	CloseTime string    `json:"close_time"`
}

func (q *Queries) UpsertBarberSchedule(ctx context.Context, arg UpsertBarberScheduleParams) (BarberSchedule, error) {
	row := q.db.QueryRow(ctx, upsertBarberSchedule,
		arg.BarberID,
		arg.Dow,
		arg.OpenTime,
		arg.CloseTime,
	)
	var i BarberSchedule
	err := row.Scan(
		&i.ID,
		&i.BarberID,
		&i.Dow,
		&i.OpenTime,
		&i.CloseTime,
	)
	return i, err
}
