// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: barbers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBarber = `-- name: CreateBarber :one
INSERT INTO barbers (user_id, name, title, bio, num)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, title, bio, num, active
`

type CreateBarberParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Title  *string   `json:"title"`
	Bio    *string   `json:"bio"`
	Num    *string   `json:"num"`
}

func (q *Queries) CreateBarber(ctx context.Context, arg CreateBarberParams) (Barber, error) {
	row := q.db.QueryRow(ctx, createBarber,
		arg.UserID,
		arg.Name,
		arg.Title,
		arg.Bio,
		arg.Num,
	)
	var i Barber
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.Bio,
		&i.Num,
		&i.Active,
	)
	return i, err
}

const getBarberByID = `-- name: GetBarberByID :one
SELECT b.id, b.user_id, b.name, b.title, b.bio, b.num, b.active, u.email FROM barbers b
JOIN users u ON u.id = b.user_id
WHERE b.id = $1
`

type GetBarberByIDRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Title  *string   `json:"title"`
	Bio    *string   `json:"bio"`
	Num    *string   `json:"num"`
	Active bool      `json:"active"`
	Email  string    `json:"email"`
}

func (q *Queries) GetBarberByID(ctx context.Context, id uuid.UUID) (GetBarberByIDRow, error) {
	row := q.db.QueryRow(ctx, getBarberByID, id)
	var i GetBarberByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.Bio,
		&i.Num,
		&i.Active,
		&i.Email,
	)
	return i, err
}

const getBarberByUserID = `-- name: GetBarberByUserID :one
SELECT id, user_id, name, title, bio, num, active FROM barbers WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetBarberByUserID(ctx context.Context, userID uuid.UUID) (Barber, error) {
	row := q.db.QueryRow(ctx, getBarberByUserID, userID)
	var i Barber
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.Bio,
		&i.Num,
		&i.Active,
	)
	return i, err
}

const listActiveBarberIDs = `-- name: ListActiveBarberIDs :many
SELECT id FROM barbers WHERE active = true ORDER BY num ASC
`

func (q *Queries) ListActiveBarberIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveBarberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBarbers = `-- name: ListBarbers :many
SELECT b.id, b.user_id, b.name, b.title, b.bio, b.num, b.active, u.email FROM barbers b
JOIN users u ON u.id = b.user_id
WHERE b.active = true
ORDER BY b.num ASC
`

type ListBarbersRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Title  *string   `json:"title"`
	Bio    *string   `json:"bio"`
	Num    *string   `json:"num"`
	Active bool      `json:"active"`
	Email  string    `json:"email"`
}

func (q *Queries) ListBarbers(ctx context.Context) ([]ListBarbersRow, error) {
	rows, err := q.db.Query(ctx, listBarbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBarbersRow{}
	for rows.Next() {
		var i ListBarbersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Title,
			&i.Bio,
			&i.Num,
			&i.Active,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBarber = `-- name: UpdateBarber :one
UPDATE barbers
SET name = $2, title = $3, bio = $4, num = $5, active = $6
WHERE id = $1
RETURNING id, user_id, name, title, bio, num, active
`

type UpdateBarberParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Title  *string   `json:"title"`
	Bio    *string   `json:"bio"`
	Num    *string   `json:"num"`
	Active bool      `json:"active"`
}

func (q *Queries) UpdateBarber(ctx context.Context, arg UpdateBarberParams) (Barber, error) {
	row := q.db.QueryRow(ctx, updateBarber,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Bio,
		arg.Num,
		arg.Active,
	)
	var i Barber
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.Bio,
		&i.Num,
		&i.Active,
	)
	return i, err
}
