// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bookingStats = `-- name: BookingStats :one
SELECT
  COUNT(*) FILTER (WHERE status = 'confirmed') AS confirmed_count,
  COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled_count,
  COUNT(*) FILTER (WHERE status = 'completed') AS completed_count,
  COALESCE(SUM(s.price_pence) FILTER (WHERE b.status IN ('confirmed','completed')), 0) AS total_pence
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.date BETWEEN $1 AND $2
`

type BookingStatsParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type BookingStatsRow struct {
	ConfirmedCount int64       `json:"confirmed_count"`
	CancelledCount int64       `json:"cancelled_count"`
	CompletedCount int64       `json:"completed_count"`
	TotalPence     interface{} `json:"total_pence"`
}

func (q *Queries) BookingStats(ctx context.Context, arg BookingStatsParams) (BookingStatsRow, error) {
	row := q.db.QueryRow(ctx, bookingStats, arg.Date, arg.Date_2)
	var i BookingStatsRow
	err := row.Scan(
		&i.ConfirmedCount,
		&i.CancelledCount,
		&i.CompletedCount,
		&i.TotalPence,
	)
	return i, err
}

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'cancelled', cancelled_at = now()
WHERE id = $1 AND status = 'confirmed'
RETURNING id, reference, user_id, barber_id, service_id, date, time_start, time_end, status, created_at, cancelled_at
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.BarberID,
		&i.ServiceID,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (reference, user_id, barber_id, service_id, date, time_start, time_end, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'confirmed')
RETURNING id, reference, user_id, barber_id, service_id, date, time_start, time_end, status, created_at, cancelled_at
`

type CreateBookingParams struct {
	Reference string      `json:"reference"`
	UserID    pgtype.UUID `json:"user_id"`
	BarberID  uuid.UUID   `json:"barber_id"`
	ServiceID uuid.UUID   `json:"service_id"`
	Date      pgtype.Date `json:"date"`
	TimeStart string      `json:"time_start"`
	TimeEnd   string      `json:"time_end"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Reference,
		arg.UserID,
		arg.BarberID,
		arg.ServiceID,
		arg.Date,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.BarberID,
		&i.ServiceID,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, reference, user_id, barber_id, service_id, date, time_start, time_end, status, created_at, cancelled_at FROM bookings WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.BarberID,
		&i.ServiceID,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getBookingByReference = `-- name: GetBookingByReference :one
SELECT id, reference, user_id, barber_id, service_id, date, time_start, time_end, status, created_at, cancelled_at FROM bookings WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetBookingByReference(ctx context.Context, reference string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByReference, reference)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.BarberID,
		&i.ServiceID,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listAllBookings = `-- name: ListAllBookings :many
SELECT b.id, b.reference, b.user_id, b.barber_id, b.service_id, b.date, b.time_start, b.time_end, b.status, b.created_at, b.cancelled_at, bar.name AS barber_name, u.first_name, u.last_name, s.name AS service_name
FROM bookings b
JOIN barbers bar ON bar.id = b.barber_id
LEFT JOIN users u ON u.id = b.user_id
JOIN services s ON s.id = b.service_id
WHERE ($1::text IS NULL OR b.status = $1)
  AND ($2::uuid IS NULL OR b.barber_id = $2)
  AND ($3::date IS NULL OR b.date = $3)
ORDER BY b.date DESC, b.time_start DESC
`

type ListAllBookingsParams struct {
	Status   *string     `json:"status"`
	BarberID pgtype.UUID `json:"barber_id"`
	Date     pgtype.Date `json:"date"`
}

type ListAllBookingsRow struct {
	ID          uuid.UUID          `json:"id"`
	Reference   string             `json:"reference"`
	UserID      pgtype.UUID        `json:"user_id"`
	BarberID    uuid.UUID          `json:"barber_id"`
	ServiceID   uuid.UUID          `json:"service_id"`
	Date        pgtype.Date        `json:"date"`
	TimeStart   string             `json:"time_start"`
	TimeEnd     string             `json:"time_end"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	BarberName  string             `json:"barber_name"`
	FirstName   *string            `json:"first_name"`
	LastName    *string            `json:"last_name"`
	ServiceName string             `json:"service_name"`
}

func (q *Queries) ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]ListAllBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllBookings, arg.Status, arg.BarberID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBookingsRow{}
	for rows.Next() {
		var i ListAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.BarberID,
			&i.ServiceID,
			&i.Date,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.BarberName,
			&i.FirstName,
			&i.LastName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForBarber = `-- name: ListBookingsForBarber :many
SELECT b.id, b.reference, b.user_id, b.barber_id, b.service_id, b.date, b.time_start, b.time_end, b.status, b.created_at, b.cancelled_at, u.first_name, u.last_name, u.phone, s.name AS service_name, s.duration_mins
FROM bookings b
LEFT JOIN users u ON u.id = b.user_id
JOIN services s ON s.id = b.service_id
WHERE b.barber_id = $1 AND b.date = $2 AND b.status != 'cancelled'
ORDER BY b.time_start ASC
`

type ListBookingsForBarberParams struct {
	BarberID uuid.UUID   `json:"barber_id"`
	Date     pgtype.Date `json:"date"`
}

type ListBookingsForBarberRow struct {
	ID           uuid.UUID          `json:"id"`
	Reference    string             `json:"reference"`
	UserID       pgtype.UUID        `json:"user_id"`
	BarberID     uuid.UUID          `json:"barber_id"`
	ServiceID    uuid.UUID          `json:"service_id"`
	Date         pgtype.Date        `json:"date"`
	TimeStart    string             `json:"time_start"`
	TimeEnd      string             `json:"time_end"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	FirstName    *string            `json:"first_name"`
	LastName     *string            `json:"last_name"`
	Phone        *string            `json:"phone"`
	ServiceName  string             `json:"service_name"`
	DurationMins int32              `json:"duration_mins"`
}

func (q *Queries) ListBookingsForBarber(ctx context.Context, arg ListBookingsForBarberParams) ([]ListBookingsForBarberRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForBarber, arg.BarberID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForBarberRow{}
	for rows.Next() {
		var i ListBookingsForBarberRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.BarberID,
			&i.ServiceID,
			&i.Date,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.ServiceName,
			&i.DurationMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForBarberDateRange = `-- name: ListBookingsForBarberDateRange :many
SELECT b.id, b.reference, b.user_id, b.barber_id, b.service_id, b.date, b.time_start, b.time_end, b.status, b.created_at, b.cancelled_at, u.first_name, u.last_name, s.name AS service_name, s.duration_mins
FROM bookings b
LEFT JOIN users u ON u.id = b.user_id
JOIN services s ON s.id = b.service_id
WHERE b.barber_id = $1 AND b.date BETWEEN $2 AND $3 AND b.status != 'cancelled'
ORDER BY b.date ASC, b.time_start ASC
`

type ListBookingsForBarberDateRangeParams struct {
	BarberID uuid.UUID   `json:"barber_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type ListBookingsForBarberDateRangeRow struct {
	ID           uuid.UUID          `json:"id"`
	Reference    string             `json:"reference"`
	UserID       pgtype.UUID        `json:"user_id"`
	BarberID     uuid.UUID          `json:"barber_id"`
	ServiceID    uuid.UUID          `json:"service_id"`
	Date         pgtype.Date        `json:"date"`
	TimeStart    string             `json:"time_start"`
	TimeEnd      string             `json:"time_end"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	FirstName    *string            `json:"first_name"`
	LastName     *string            `json:"last_name"`
	ServiceName  string             `json:"service_name"`
	DurationMins int32              `json:"duration_mins"`
}

func (q *Queries) ListBookingsForBarberDateRange(ctx context.Context, arg ListBookingsForBarberDateRangeParams) ([]ListBookingsForBarberDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForBarberDateRange, arg.BarberID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForBarberDateRangeRow{}
	for rows.Next() {
		var i ListBookingsForBarberDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.BarberID,
			&i.ServiceID,
			&i.Date,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.FirstName,
			&i.LastName,
			&i.ServiceName,
			&i.DurationMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForUser = `-- name: ListBookingsForUser :many
SELECT b.id, b.reference, b.user_id, b.barber_id, b.service_id, b.date, b.time_start, b.time_end, b.status, b.created_at, b.cancelled_at, bar.name AS barber_name, s.name AS service_name
FROM bookings b
JOIN barbers bar ON bar.id = b.barber_id
JOIN services s ON s.id = b.service_id
WHERE b.user_id = $1
ORDER BY b.date DESC, b.time_start DESC
`

type ListBookingsForUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Reference   string             `json:"reference"`
	UserID      pgtype.UUID        `json:"user_id"`
	BarberID    uuid.UUID          `json:"barber_id"`
	ServiceID   uuid.UUID          `json:"service_id"`
	Date        pgtype.Date        `json:"date"`
	TimeStart   string             `json:"time_start"`
	TimeEnd     string             `json:"time_end"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	BarberName  string             `json:"barber_name"`
	ServiceName string             `json:"service_name"`
}

func (q *Queries) ListBookingsForUser(ctx context.Context, userID pgtype.UUID) ([]ListBookingsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForUserRow{}
	for rows.Next() {
		var i ListBookingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.BarberID,
			&i.ServiceID,
			&i.Date,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.BarberName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedBookingsForBarberDate = `-- name: ListConfirmedBookingsForBarberDate :many
SELECT time_start, time_end FROM bookings
WHERE barber_id = $1 AND date = $2 AND status = 'confirmed'
`

type ListConfirmedBookingsForBarberDateParams struct {
	BarberID uuid.UUID   `json:"barber_id"`
	Date     pgtype.Date `json:"date"`
}

type ListConfirmedBookingsForBarberDateRow struct {
	TimeStart string `json:"time_start"`
	TimeEnd   string `json:"time_end"`
}

// Confirmed bookings for a barber on a date — used by availability engine.
func (q *Queries) ListConfirmedBookingsForBarberDate(ctx context.Context, arg ListConfirmedBookingsForBarberDateParams) ([]ListConfirmedBookingsForBarberDateRow, error) {
	rows, err := q.db.Query(ctx, listConfirmedBookingsForBarberDate, arg.BarberID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfirmedBookingsForBarberDateRow{}
	for rows.Next() {
		var i ListConfirmedBookingsForBarberDateRow
		if err := rows.Scan(&i.TimeStart, &i.TimeEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
