// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_products.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBookingProduct = `-- name: CreateBookingProduct :one
INSERT INTO booking_products (booking_id, product_id, qty, price_pence)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, product_id, qty, price_pence
`

type CreateBookingProductParams struct {
	BookingID  uuid.UUID `json:"booking_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Qty        int32     `json:"qty"`
	PricePence int32     `json:"price_pence"`
}

func (q *Queries) CreateBookingProduct(ctx context.Context, arg CreateBookingProductParams) (BookingProduct, error) {
	row := q.db.QueryRow(ctx, createBookingProduct,
		arg.BookingID,
		arg.ProductID,
		arg.Qty,
		arg.PricePence,
	)
	var i BookingProduct
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ProductID,
		&i.Qty,
		&i.PricePence,
	)
	return i, err
}

const listBookingProducts = `-- name: ListBookingProducts :many
SELECT bp.id, bp.booking_id, bp.product_id, bp.qty, bp.price_pence, p.name AS product_name
FROM booking_products bp
JOIN products p ON p.id = bp.product_id
WHERE bp.booking_id = $1
`

type ListBookingProductsRow struct {
	ID          uuid.UUID `json:"id"`
	BookingID   uuid.UUID `json:"booking_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Qty         int32     `json:"qty"`
	PricePence  int32     `json:"price_pence"`
	ProductName string    `json:"product_name"`
}

func (q *Queries) ListBookingProducts(ctx context.Context, bookingID uuid.UUID) ([]ListBookingProductsRow, error) {
	rows, err := q.db.Query(ctx, listBookingProducts, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingProductsRow{}
	for rows.Next() {
		var i ListBookingProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ProductID,
			&i.Qty,
			&i.PricePence,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
