// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (type, entity_id, bucket_key, public_url, sort_order, alt_text, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, entity_id, bucket_key, public_url, sort_order, alt_text, uploaded_by, created_at
`

type CreateMediaParams struct {
	Type       string      `json:"type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	BucketKey  string      `json:"bucket_key"`
	PublicUrl  string      `json:"public_url"`
	SortOrder  int32       `json:"sort_order"`
	AltText    *string     `json:"alt_text"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Type,
		arg.EntityID,
		arg.BucketKey,
		arg.PublicUrl,
		arg.SortOrder,
		arg.AltText,
		arg.UploadedBy,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityID,
		&i.BucketKey,
		&i.PublicUrl,
		&i.SortOrder,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const deleteMediaForEntity = `-- name: DeleteMediaForEntity :exec
DELETE FROM media WHERE type = $1 AND entity_id = $2
`

type DeleteMediaForEntityParams struct {
	Type     string      `json:"type"`
	EntityID pgtype.UUID `json:"entity_id"`
}

func (q *Queries) DeleteMediaForEntity(ctx context.Context, arg DeleteMediaForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteMediaForEntity, arg.Type, arg.EntityID)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, type, entity_id, bucket_key, public_url, sort_order, alt_text, uploaded_by, created_at FROM media WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityID,
		&i.BucketKey,
		&i.PublicUrl,
		&i.SortOrder,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaForEntity = `-- name: GetMediaForEntity :one
SELECT id, type, entity_id, bucket_key, public_url, sort_order, alt_text, uploaded_by, created_at FROM media WHERE type = $1 AND entity_id = $2 LIMIT 1
`

type GetMediaForEntityParams struct {
	Type     string      `json:"type"`
	EntityID pgtype.UUID `json:"entity_id"`
}

func (q *Queries) GetMediaForEntity(ctx context.Context, arg GetMediaForEntityParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaForEntity, arg.Type, arg.EntityID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityID,
		&i.BucketKey,
		&i.PublicUrl,
		&i.SortOrder,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaByType = `-- name: ListMediaByType :many
SELECT id, type, entity_id, bucket_key, public_url, sort_order, alt_text, uploaded_by, created_at FROM media WHERE type = $1 ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListMediaByType(ctx context.Context, type_ string) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EntityID,
			&i.BucketKey,
			&i.PublicUrl,
			&i.SortOrder,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaSortOrder = `-- name: UpdateMediaSortOrder :exec
UPDATE media SET sort_order = $2 WHERE id = $1
`

type UpdateMediaSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateMediaSortOrder(ctx context.Context, arg UpdateMediaSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateMediaSortOrder, arg.ID, arg.SortOrder)
	return err
}
