// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Barber struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Title  *string   `json:"title"`
	Bio    *string   `json:"bio"`
	Num    *string   `json:"num"`
	Active bool      `json:"active"`
}

type BarberSchedule struct {
	ID        uuid.UUID `json:"id"`
	BarberID  uuid.UUID `json:"barber_id"`
	Dow       int32     `json:"dow"`
	OpenTime  string    `json:"open_time"`
	CloseTime string    `json:"close_time"`
}

type Booking struct {
	ID          uuid.UUID          `json:"id"`
	Reference   string             `json:"reference"`
	UserID      pgtype.UUID        `json:"user_id"`
	BarberID    uuid.UUID          `json:"barber_id"`
	ServiceID   uuid.UUID          `json:"service_id"`
	Date        pgtype.Date        `json:"date"`
	TimeStart   string             `json:"time_start"`
	TimeEnd     string             `json:"time_end"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
}

type BookingProduct struct {
	ID         uuid.UUID `json:"id"`
	BookingID  uuid.UUID `json:"booking_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Qty        int32     `json:"qty"`
	PricePence int32     `json:"price_pence"`
}

type Medium struct {
	ID         uuid.UUID          `json:"id"`
	Type       string             `json:"type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	BucketKey  string             `json:"bucket_key"`
	PublicUrl  string             `json:"public_url"`
	SortOrder  int32              `json:"sort_order"`
	AltText    *string            `json:"alt_text"`
	UploadedBy pgtype.UUID        `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	PricePence int32     `json:"price_pence"`
	Active     bool      `json:"active"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID           uuid.UUID `json:"id"`
	Num          *string   `json:"num"`
	Name         string    `json:"name"`
	NameHtml     *string   `json:"name_html"`
	Description  *string   `json:"description"`
	DurationMins int32     `json:"duration_mins"`
	PricePence   int32     `json:"price_pence"`
	Active       bool      `json:"active"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    *string            `json:"first_name"`
	LastName     *string            `json:"last_name"`
	Phone        *string            `json:"phone"`
	Role         string             `json:"role"`
	ReminderOpt  bool               `json:"reminder_opt"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
