// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price_pence)
VALUES ($1, $2)
RETURNING id, name, price_pence, active
`

type CreateProductParams struct {
	Name       string `json:"name"`
	PricePence int32  `json:"price_pence"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PricePence)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_pence, active FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_pence, active FROM products WHERE active = true ORDER BY name ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PricePence,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, price_pence = $3, active = $4
WHERE id = $1
RETURNING id, name, price_pence, active
`

type UpdateProductParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	PricePence int32     `json:"price_pence"`
	Active     bool      `json:"active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.PricePence,
		arg.Active,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}
