// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :one
INSERT INTO services (num, name, name_html, description, duration_mins, price_pence)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, num, name, name_html, description, duration_mins, price_pence, active
`

type CreateServiceParams struct {
	Num          *string `json:"num"`
	Name         string  `json:"name"`
	NameHtml     *string `json:"name_html"`
	Description  *string `json:"description"`
	DurationMins int32   `json:"duration_mins"`
	PricePence   int32   `json:"price_pence"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Num,
		arg.Name,
		arg.NameHtml,
		arg.Description,
		arg.DurationMins,
		arg.PricePence,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Num,
		&i.Name,
		&i.NameHtml,
		&i.Description,
		&i.DurationMins,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, num, name, name_html, description, duration_mins, price_pence, active FROM services WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Num,
		&i.Name,
		&i.NameHtml,
		&i.Description,
		&i.DurationMins,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, num, name, name_html, description, duration_mins, price_pence, active FROM services WHERE active = true ORDER BY num ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Num,
			&i.Name,
			&i.NameHtml,
			&i.Description,
			&i.DurationMins,
			&i.PricePence,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET num = $2, name = $3, name_html = $4, description = $5,
    duration_mins = $6, price_pence = $7, active = $8
WHERE id = $1
RETURNING id, num, name, name_html, description, duration_mins, price_pence, active
`

type UpdateServiceParams struct {
	ID           uuid.UUID `json:"id"`
	Num          *string   `json:"num"`
	Name         string    `json:"name"`
	NameHtml     *string   `json:"name_html"`
	Description  *string   `json:"description"`
	DurationMins int32     `json:"duration_mins"`
	PricePence   int32     `json:"price_pence"`
	Active       bool      `json:"active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Num,
		arg.Name,
		arg.NameHtml,
		arg.Description,
		arg.DurationMins,
		arg.PricePence,
		arg.Active,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Num,
		&i.Name,
		&i.NameHtml,
		&i.Description,
		&i.DurationMins,
		&i.PricePence,
		&i.Active,
	)
	return i, err
}
